### ISSUE TITLE
querying clusterServices perfcounter does not work if "interval" is set

### ISSUE THREAD

**Issue by anfoe1111** [ConSol-Monitoring/check_vsphere#26]
When trying to do a "perf" query like "--vimtype ClusterComputeResource --vimname _abcde_ --perfcounter clusterServices:effectivemem:average" the query will throw an error:

```
UNKNOWN - Unhandled exception: (vmodl.fault.InvalidArgument) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'A specified parameter was not correct: querySpec.interval',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) [],
   invalidProperty = 'querySpec.interval'
}
Traceback (most recent call last):
  File "/omd/sites/naemon/local/lib/python/checkvsphere/cli.py", line 86, in main
    run()
  File "/omd/sites/naemon/local/lib/python/checkvsphere/cli.py", line 58, in run
    runner.run()
  File "/omd/sites/naemon/local/lib/python/checkvsphere/vcmd/perf.py", line 134, in run
    values = get_perf_values(args, obj, metricId)[0]
  File "/omd/sites/naemon/local/lib/python/checkvsphere/vcmd/perf.py", line 193, in get_perf_values
    perfData = perfMgr.QueryPerf(querySpec=perfQuerySpec)
  File "/omd/sites/naemon/local/lib/python/pyVmomi/VmomiSupport.py", line 614, in <lambda>
    self.f(*(self.args + (obj,) + args), **kwargs)
  File "/omd/sites/naemon/local/lib/python/pyVmomi/VmomiSupport.py", line 387, in _InvokeMethod
    return self._stub.InvokeMethod(self, info, args)
  File "/omd/sites/naemon/local/lib/python/pyVmomi/SoapAdapter.py", line 1472, in InvokeMethod
    raise obj  # pylint: disable-msg=E0702
pyVmomi.VmomiSupport.vmodl.fault.InvalidArgument: (vmodl.fault.InvalidArgument) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'A specified parameter was not correct: querySpec.interval',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) [],
   invalidProperty = 'querySpec.interval'
```

When commenting line 188 of file vcmd/perf.py the query is successful:

```
...
177 def get_perf_values(args, obj, metricId):
178     si = args._si
179
180     perfMgr = si.content.perfManager
181
182     perfQuerySpec = []
183     perfQuerySpec.append(
184         vim.PerformanceManager.QuerySpec(
185             maxSample=1,
186             entity=obj,
187             metricId=[metricId],
188             **#intervalId=args.interval,**
189         )
190     )
...
```

It seems, the "clusterServices" PerfCounters don't want to see the interval.

**Comment by anfoe1111** [comment]
OK, issue can be closed. For aggregated functions a "historical" interval (e.g. 300) is to be used. After changing this in the template, everything is working fine.
